In [1]:
import pandas as pd

In [2]:
walmart=pd.read_csv(r"C:\Users\EliteBook\Downloads\New folder\Walmart_Sales.csv")
walmart

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
...,...,...,...,...,...,...,...,...
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [7]:
walmart.head(10)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
5,1,12-03-2010,1439541.59,0,57.79,2.667,211.380643,8.106
6,1,19-03-2010,1472515.79,0,54.58,2.720,211.215635,8.106
7,1,26-03-2010,1404429.92,0,51.45,2.732,211.018042,8.106
8,1,02-04-2010,1594968.28,0,62.27,2.719,210.820450,7.808
9,1,09-04-2010,1545418.53,0,65.86,2.770,210.622857,7.808

In [8]:
walmart.info

<bound method DataFrame.info of       Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0         1  05-02-2010    1643690.90             0        42.31       2.572
1         1  12-02-2010    1641957.44             1        38.51       2.548
2         1  19-02-2010    1611968.17             0        39.93       2.514
3         1  26-02-2010    1409727.59             0        46.63       2.561
4         1  05-03-2010    1554806.68             0        46.50       2.625
...     ...         ...           ...           ...          ...         ...
6430     45  28-09-2012     713173.95             0        64.88       3.997
6431     45  05-10-2012     733455.07             0        64.89       3.985
6432     45  12-10-2012     734464.36             0        54.47       4.000
6433     45  19-10-2012     718125.53             0        56.47       3.969
6434     45  26-10-2012     760281.43             0        58.85       3.882

             CPI  Unemployment
0     211.096358         8.106
1     211.242170         8.106
2     211.289143         8.106
3     211.319643         8.106
4     211.350143         8.106
...          ...           ...
6430  192.013558         8.684
6431  192.170412         8.667
6432  192.327265         8.667
6433  192.330854         8.667
6434  192.308899         8.667

[6435 rows x 8 columns]>

In [18]:
 walmart['Store'].value_counts().head()

Store
1     143
24    143
26    143
27    143
28    143
Name: count, dtype: int64

In [20]:
 walmart.dtype()

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [5]:
walmart.set_index("Unemployment", inplace=True)

In [6]:
walmart.head(10)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI
Unemployment,,,,,,,
8.106,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358
8.106,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170
8.106,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143
8.106,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643
8.106,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143
8.106,1,12-03-2010,1439541.59,0,57.79,2.667,211.380643
8.106,1,19-03-2010,1472515.79,0,54.58,2.720,211.215635
8.106,1,26-03-2010,1404429.92,0,51.45,2.732,211.018042
7.808,1,02-04-2010,1594968.28,0,62.27,2.719,210.820450
7.808,1,09-04-2010,1545418.53,0,65.86,2.770,210.622857

In [8]:
walmart.set_index("CPI",inplace=False)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price
CPI,,,,,,
211.096358,1,05-02-2010,1643690.90,0,42.31,2.572
211.242170,1,12-02-2010,1641957.44,1,38.51,2.548
211.289143,1,19-02-2010,1611968.17,0,39.93,2.514
211.319643,1,26-02-2010,1409727.59,0,46.63,2.561
211.350143,1,05-03-2010,1554806.68,0,46.50,2.625
...,...,...,...,...,...,...
192.013558,45,28-09-2012,713173.95,0,64.88,3.997
192.170412,45,05-10-2012,733455.07,0,64.89,3.985
192.327265,45,12-10-2012,734464.36,0,54.47,4.000
192.330854,45,19-10-2012,718125.53,0,56.47,3.969
192.308899,45,26-10-2012,760281.43,0,58.85,3.882

In [10]:
walmart.groupby("Weekly_Sales")

In [4]:
walmart.groupby("Weekly_Sales").count().head(2)

,Store,Date,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
Weekly_Sales,,,,,,,
209986.25,1,1,1,1,1,1,1
213538.32,1,1,1,1,1,1,1

walmart.groupby("Store")["Weekly_Sales"].sum()

In [5]:
walmart

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
...,...,...,...,...,...,...,...,...
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [6]:
walmart.orderby("Date")

AttributeError: 'DataFrame' object has no attribute 'orderby'

In [17]:
walmart.sort_values(by="Date", descending=False)

TypeError: DataFrame.sort_values() got an unexpected keyword argument 'descending'

In [19]:
walmart .sort_values(by="Weekly_Sales", ascending=False)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
1905,14,24-12-2010,3818686.45,0,30.59,3.141,182.544590,8.724
2763,20,24-12-2010,3766687.43,0,25.17,3.141,204.637673,7.484
1333,10,24-12-2010,3749057.69,0,57.06,3.236,126.983581,9.003
527,4,23-12-2011,3676388.98,0,35.92,3.103,129.984548,5.143
1762,13,24-12-2010,3595903.20,0,34.90,2.846,126.983581,7.795
...,...,...,...,...,...,...,...,...
4671,33,02-12-2011,220060.35,0,59.12,3.701,129.845967,8.010
4623,33,31-12-2010,219804.85,1,52.91,3.148,127.087677,9.265
4675,33,30-12-2011,215359.21,1,51.60,3.428,130.071032,8.010
4614,33,29-10-2010,213538.32,0,71.34,3.130,126.436419,9.265
4619,33,03-12-2010,209986.25,0,52.82,3.041,126.731333,9.265